project_box/apps/users/urls.py
"""
URL Configuration.

URL configurations for the terms application.
"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    HomeAPIView,
    register
)

# Specify a namespace
app_name = "users"


urlpatterns = [
    path(
        '',
        HomeAPIView.as_view(),
        name='index'),

    path(
        'login/',
        LoginView.as_view(template_name='components/user/login.html'), name='login'),
    path(
        'signup/', register, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

project_box/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('project_box.apps.authentication.urls',
                      'authentication'), namespace='authentication')),
    path('mods/', include(('project_box.apps.mods.urls',
                          'mods'), namespace='mods')),
    # Misc
    path('tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django_countries.fields import CountryField
from mods.models import Mod


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=120, blank=True)
    country = CountryField(blank=True)
    bio = models.TextField(max_length=2000, blank=True, null=True)
    twitter = models.CharField(max_length=25, blank=True, help_text='Enter your Twitter username. NOT the link.')
    simulators = models.ManyToManyField(Mod, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile')
    header_image = models.ImageField(default='default.jpg', upload_to='profile/header/')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # img = Image.open(self.image.path)

        # if img.height > 1080 or img.width > 1920:
        #     output_size = (1080, 1920)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)

project_box/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = {'country', 'bio', 'twitter', 'image', 'header_image'}

users/views.py
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin  # UserPassesTestMixin

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import DetailView, ListView, UpdateView
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

from mixins.template import HeaderMixin

from mods.models import Mod, ModsListConnector, ModsListName, ModsLike


def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Account created for {username}!')
                return redirect('login')
        else:
            form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})
    else:
        messages.success(request, 'Account created successfully. Welcome!')
        return redirect('/profile/' + request.user.username)


class ProfileView(LoginRequiredMixin, HeaderMixin, DetailView):
    model = User
    template_name = 'users/profile.html'

    # Set header tags
    title = 'Profile - <username>'
    description = 'Simbox profile of <username>'
    og_image = '<profile><image><url>'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['list_names'] = ModsListName.objects.filter(
                list_owner=User.objects.get(id=self.get_object().id)
        )

        context['likes'] = ModsLike.objects.filter(
            user_id=User.objects.get(id=self.get_object().id)
        )

        return context


class ProfileModsView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile_mods.html'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return User.objects.get(username=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['mods'] = Mod.objects.filter(
                author=User.objects.get(pk=self.get_object().id)
        )

        return context


class ProfileListsView(LoginRequiredMixin, ListView):
    model = ModsListConnector
    template_name = 'users/profile_list_detail.html'

    def get_queryset(self):
        return ModsListConnector.objects.filter(
            list_id=self.kwargs.get('id')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['object'] = User.objects.get(
            username=self.kwargs.get('username')
        )

        return context


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/update_profile.html'

    def get(self, request):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {'u_form': u_form, 'p_form': p_form}
        return render(request, 'users/update_profile.html', context)

    def post(self, request, *args, **kwargs):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            messages.success(request, 'Your account has been updated!')
            return redirect('/profile/' + request.user.username)


class ProfileUpdatePassword(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'users/update_profile.html'

    def get_success_url(self) -> str:
        messages.success(self.request, 'Password updated successfully.')
        return reverse_lazy('profile', kwargs={'username': self.request.user})

templates/components/user/login.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block maincontent %}
<!-- MainContent -->
<section class="sign-in-page">
  {% comment %} <video autoplay muted loop id="myVideo">
    <source src="{%static 'images/bg-video.mp4' %}" type="video/mp4" />
  </video> {% endcomment %}
  <div class="container">
    <div
      class="row justify-content-center align-items-center height-self-center"
    >
      <div class="col-lg-5 col-md-12 align-self-center">
        <div class="sign-user_card">
          <div class="sign-in-page-data">
            <div class="sign-in-from w-100 m-auto">
              <h3 class="mb-3 text-center">Sign in</h3>
              {% if messages %}
              {% for message in messages %}
              {% if message.tags == "success" %}
              <p class="successField">
              {{message}}
              </p>
              {%else%}
              <p class="errorField">
              {{message}}
              </p>
              {% endif %}
              {% endfor %}
              {%endif%}
              <form class="mt-4" method="post">
                {% csrf_token %} {{ form|crispy }}

                <div class="sign-info">
                <br>
                  <button type="submit" class="btn btn-hover">Sign in</button><br>
                </div>
              </form>
            </div>
          </div>
          <div class="mt-3">
            <div class="d-flex justify-content-start links">
              Don't have an account?
              <a href="{%url 'authentication:signup' %}" class="text-primary ml-2">Sign Up</a>
            </div>
            <div class="d-flex justify-content-start links">
              <a href="#" class="f-link"
                >Forgot your password?</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}

templates/components/user/register.html
{% extends "base.html" %}
{% load static %} 
{% load crispy_forms_tags %} 
{%block maincontent %}
<!-- MainContent -->
<section class="sign-in-page">
  <div class="container">
    <div
      class="row justify-content-center align-items-center"
    >
      <div class="col-lg-6 col-md-12 align-self-center mt-8">
        <div class="sign-user_card" style="margin:160px 0;" >
          <div class="sign-in-page-data">
            <div class="sign-in-from w-100 m-auto">
              <h3 class="text-center">Register</h3>
              <form class="mt-12" method="post">
                <br />
                {% csrf_token %} {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-hover my-2">
                  Sign Up
                </button>
              </form>
            </div>
          </div>
          <div class="mt-3">
            <div class="d-flex justify-content-start links">
              Already have an account?
              <a href="{%url 'authentication:login' %}" class="text-primary ml-2">Sign In</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}