project_box/apps/authentication/urls.py
"""
URL Configuration.

URL configurations for the terms application.
"""
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.views.generic.base import TemplateView
from .views import (
    HomeAPIView,
    VerifyAPIView,
    SignUpView,
    UserUpdateView,
    ProfileModsAPIView,
    CustomLoginView,
    ContactView
)

# Specify a namespace
app_name = "authentication"


urlpatterns = [
    path(
        '',
        HomeAPIView.as_view(),
        name='index'),
    path(
        'login/',
        CustomLoginView.as_view(),
        name='login'),
    path(
        'signup/',
        SignUpView.as_view(),
        name='signup'),
    path('verify/<token>/',
         VerifyAPIView.as_view(),
         name='verify_email'),
    path('profile/',
         UserUpdateView.as_view(),
         name='profile'),
    path('profile/<username>/',
         ProfileModsAPIView.as_view(),
         name='profile-mods'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
    path('guide/',
         TemplateView.as_view(template_name="components/extras/guide.html"),
         name='guide'),
    path('terms/',
         TemplateView.as_view(template_name="components/extras/terms.html"),
         name='terms'),
    path('contact/',
         ContactView.as_view(),
         name='contact'),
]

project_box/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('project_box.apps.authentication.urls',
                      'authentication'), namespace='authentication')),
    path('mods/', include(('project_box.apps.mods.urls',
                          'mods'), namespace='mods')),
    # Misc
    path('tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

templates/components/layout/footer.html
   {%load static%}
   <footer id="contact" class="footer-one iq-bg-dark">
      <!-- Address -->
      <div class="footer-top">
        <div class="container-fluid">
          <div class="row footer-standard">
            <div class="col-lg-7">
              <div class="widget text-left">
                <div class="menu-footer-link-1-container">
                  <ul id="menu-footer-link-1" class="menu p-0">
                    <li
                      id="menu-item-7314"
                      class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7314"
                    >
                      <a href="{% url 'authentication:terms' %}">Terms Of Use</a>
                    </li>
                    <li
                      id="menu-item-7316"
                      class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7316"
                    >
                      <a href="{% url 'authentication:guide' %}">Community Guidelines</a>
                    </li>
                    {% comment %} <li
                      id="menu-item-7118"
                      class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118"
                    >
                      <a href="faq.html">FAQ</a>
                    </li>
                    <li
                      id="menu-item-7118"
                      class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118"
                    >
                      <a href="#">Favourites List</a>
                    </li> {% endcomment %}
                  </ul>
                </div>
              </div>
              <div class="widget text-left">
                <div class="textwidget">
                  <p>
                    <small
                      >© 2021 Simbox. All Rights Reserved. All images and files
                      on this platform are trademarks of, and all related images
                      and content are the property of, Simbox Inc. Duplication
                      and copy of this is strictly prohibited. All rights
                      reserved.</small
                    >
                  </p>
                </div>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 mt-4 mt-lg-0">
              <h6 class="footer-link-title">Follow Us :</h6>
              <ul class="info-share">
                <li>
                  <a target="_blank" href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a target="_blank" href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a target="_blank" href="#"
                    ><i class="fa fa-google-plus"></i
                  ></a>
                </li>
                {% comment %} <li>
                  <a target="_blank" href="#"><i class="fa fa-github"></i></a>
                </li> {% endcomment %}
              </ul>
            </div>
            {% comment %} <div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
              <div class="widget text-left">
                <div class="textwidget">
                  <h6 class="footer-link-title">Simbox App</h6>
                  <div class="d-flex align-items-center">
                    <a class="app-image" href="#">
                      <img
                        src="{% static 'images/footer/01.jpg'%}"
                        alt="play-store"
                      /> </a
                    ><br />
                    <a class="ml-3 app-image" href="#"
                      ><img
                        src="{% static 'images/footer/02.jpg'%}"
                        alt="app-store"
                    /></a>
                  </div>
                </div>
              </div>
            </div> {% endcomment %}
          </div>
        </div>
      </div>
      <!-- Address END -->
    </footer>

templates/components/layout/meta.html
<title>{{ meta_tags.title }}</title>
<meta name="description" content="{{ meta_tags.description }}">
<meta name="keywords" content="{{ meta_tags.keywords }}">

<meta property="og:title" content="{{ meta_tags.title }}">
<meta property="og:description" content="{{ meta_tags.description }}">

{% if meta_tags.og_image %}
<meta property="og:image" content="{{ meta_tags.og_image }}">
{% endif %}

{% if meta_tags.og_site_name %}
<meta property="og:url" content="{{ meta_tags.url }}">
{% endif %}