project_box/apps/mods/urls.py
"""
URL Configuration.

URL configurations for the terms application.
"""
from django.urls import path
from .views import (
    CategoryView,
    ModDetailView,
    AddModView,
    SubTypeView,
    # EditModView,
    # DeleteModView,
    ModsListView
)

# Specify a namespace
app_name = "mods"

urlpatterns = [
    # Mods link
    path(f'<int:pk>/', ModDetailView.as_view(), name='mod-detail'),
    path(f'simulator/<int:pk>/', CategoryView.as_view(), name='category'),
    path(f'simulator/<int:sim>/type/<int:type_>/', SubTypeView.as_view(), name='subtype'),
    path(f'upload/', AddModView.as_view(), name='create-mod'),
    # path(f'<int:pk>/update/', EditModView.as_view(), name='edit-mod'),
    # path(f'<int:pk>/delete/', DeleteModView.as_view(), name='delete-mod'),
    path(f'', ModsListView.as_view(), name='mods-list'),
]

project_box/apps/users/urls.py
"""
URL Configuration.

URL configurations for the terms application.
"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    HomeAPIView,
    register
)

# Specify a namespace
app_name = "users"


urlpatterns = [
    path(
        '',
        HomeAPIView.as_view(),
        name='index'),

    path(
        'login/',
        LoginView.as_view(template_name='components/user/login.html'), name='login'),
    path(
        'signup/', register, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

project_box/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('project_box.apps.authentication.urls',
                      'authentication'), namespace='authentication')),
    path('mods/', include(('project_box.apps.mods.urls',
                          'mods'), namespace='mods')),
    # Misc
    path('tinymce/', include('tinymce.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

project_box/apps/mods/forms.py
from django import forms
from .models import Mod, SubType, Type


class ModCreateForm(forms.ModelForm):
    simulator_ = forms.ModelChoiceField(queryset=Type.objects.all().distinct())
    category_ = forms.ModelChoiceField(queryset=SubType.objects.all().distinct())
    screenshots = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':
                                                                         True}))
    agree_to_terms_and_conditions = forms.BooleanField(required=True)

    class Meta:
        model = Mod
        fields = ['title', 'simulator_', 'category_', 'description',
                  'header_image', 'cover_image', 'screenshots', 'mod_file']
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ModCreateForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        if Mod.objects.filter(title=title).exists():
            raise forms.ValidationError("A mod with this title already exists.")
        return title

mods/views.py
from django.http.response import Http404
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.db import transaction

from mixins.template import HeaderMixin

from .forms import (
    AddModToListForm,
    CreateNewListForm,
    CreateCommentForm,
    ModCreateForm,
    ModFormSet
)

from .models import (
    Mod,
    ModsLike,
    ModsView,
    ModsGallery,
    ModsListName,
    ModsListConnector,
    ModComments,
    ModsDownloadsCounter
)


class ModsDetailView(LoginRequiredMixin, HeaderMixin, DetailView):
    model = Mod

    title = '<title>'
    description = 'Download <title> now for your flight simulator!'
    og_image = '<image><url>'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        mod_instance = self.get_object()

        context['screenshots'] = ModsGallery.objects.filter(
            mod=self.kwargs['pk']
        )[:5]

        context['like_count'] = ModsLike.objects.filter(
            mod_id=mod_instance
        ).count()

        context['view_count'] = ModsView.objects.filter(
            mod_id=mod_instance
        ).count()

        context['downloads'] = ModsDownloadsCounter.objects.filter(
            mod_id=mod_instance
        ).count()

        context['comments'] = ModComments.objects.filter(
            mod_id=mod_instance
        )

        if self.request.user.is_authenticated:
            # Add context data
            context['has_liked'] = ModsLike.objects.filter(
                mod_id=self.kwargs['pk'],
                user_id=self.request.user
            )

            context['lists'] = ModsListName.objects.filter(
                list_owner=self.request.user
            )

            # Populate dropdown with mod lists from user
            add_to_list_form = AddModToListForm()
            add_to_list_form.fields['list_name'].queryset = ModsListName.objects.filter(list_owner=self.request.user)
            context['add_to_list_form'] = add_to_list_form

            context['create_new_list_form'] = CreateNewListForm()
            context['create_comment_form'] = CreateCommentForm()

        # Save view as new if not already existent
        ip = self.get_client_ip()
        ModsView.objects.get_or_create(mod_id=mod_instance, IPAddress=ip)

        return context

    # Handle post requests (mainly Ajax)
    def post(self, request, *args, **kwargs):
        mod = self.get_object()
        user = request.user
        ajax_data = request.POST

        # Create a list for mods
        if (ajax_data.get('action') == 'create-list'):
            new_list_form = CreateNewListForm(request.POST)

            if new_list_form.is_valid():
                obj = ModsListName()
                obj.list_name = new_list_form.cleaned_data['list_name']
                obj.list_owner = user
                obj.save()

                return JsonResponse({'list_id': obj.id, 'list_name': obj.list_name}, status=200)

        # Add mod to list
        elif (ajax_data.get('action') == 'add-to-list'):
            add_to_list_form = AddModToListForm(request.POST)

            if add_to_list_form.is_valid():
                obj = ModsListConnector()
                obj.list_id = ModsListName.objects.filter(list_name=add_to_list_form.cleaned_data['list_name']).first()
                obj.mod_id = mod
                obj.user_id = user
                obj.save()

                return JsonResponse({'message': f'{mod.title} has been added to list "{obj.list_id.list_name}"'}, status=200)

        # Add or delete like
        elif (ajax_data.get('action') == 'like'):
            # Save new like if it doesn't exist. If it exists, delete it.
            if(ModsLike.objects.filter(mod_id=mod, user_id=user).exists()):
                ModsLike.objects.get(mod_id=mod, user_id=user).delete()
                return JsonResponse({'message': 'Removed like.'}, status=200)
            else:
                ModsLike(mod_id=mod, user_id=user).save()
                return JsonResponse({'message': 'Thank you for your like!'}, status=200)

        # Save comment
        elif (ajax_data.get('action') == 'save-comment'):
            create_comment_form = CreateCommentForm(request.POST)

            if create_comment_form.is_valid():
                obj = ModComments()
                obj.text = create_comment_form.cleaned_data['text']
                obj.user_id = user
                obj.mod_id = mod
                obj.save()

                return JsonResponse({'message': 'Comment has been saved.'}, status=200)
        
        # Delete comment
        elif (ajax_data.get('action') == 'delete-comment'):
            comment = ModComments.objects.filter(id=ajax_data.get('comment')).first()

            if (user == comment.user_id):
                comment.delete()
                return JsonResponse({'message': 'Comment has been deleted.'}, status=200)
            else:
                return JsonResponse({"status", "Forbidden access."}, status=500)

        # Download counter
        elif (ajax_data.get('action') == 'download'):
            ip = self.get_client_ip()
            ModsDownloadsCounter.objects.get_or_create(
                mod_id=mod,
                IPAddress=ip
            )
            return JsonResponse({'message': 'Comment has been deleted.'}, status=200)

        else:
            Http404("Something went wrong during the request!")

    def get_client_ip(self):
        '''Get client IP address to allow for unique views on each mod.'''
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        return ip


class ModsListView(LoginRequiredMixin, ListView):
    model = Mod


class CreateModView(LoginRequiredMixin, CreateView):
    model = Mod
    form_class = ModCreateForm

    def get_context_data(self, **kwargs):
        context = super(CreateModView, self).get_context_data(**kwargs)

        if self.request.POST:
            context['images'] = ModFormSet(self.request.POST)
            context['images'].full_clean()
        else:
            context['images'] = ModFormSet()
        return context

    def form_valid(self, form):
        images_formset = ModFormSet(self.request.POST, self.request.FILES, instance=form.instance)

        form.instance.author = self.request.user

        with transaction.atomic():
            if images_formset.is_valid():
                response = super().form_valid(form)
                images_formset.mod = self.object
                images_formset.save()

                return response
            else:
                return super(EditModView, self).form_invalid(form)

    def get_success_url(self) -> str:
        return reverse_lazy('mod-detail', kwargs={'pk': self.object.pk})


class EditModView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mod
    form_class = ModCreateForm

    def get_context_data(self, **kwargs):
        context = super(EditModView, self).get_context_data(**kwargs)

        if self.request.POST:
            context['images'] = ModFormSet(self.request.POST, instance=self.object)
            context['images'].full_clean()
        else:
            context['images'] = ModFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        images_formset = ModFormSet(self.request.POST, self.request.FILES, instance=form.instance)

        form.instance.author = self.request.user

        with transaction.atomic():
            if images_formset.is_valid():
                images_formset.mod = self.object
                images_formset.save()

                response = super().form_valid(form)
                return response
            else:
                return super(EditModView, self).form_invalid(form)

    # Check if requesting user is the author of the mod
    def test_func(self):
        mod = self.get_object()
        return self.request.user == mod.author

    def get_success_url(self) -> str:
        return reverse_lazy('mod-detail', kwargs={'pk': self.object.pk})


class DeleteModView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mod

    def test_func(self):
        mod = self.get_object()
        return self.request.user == mod.author

    def get_success_url(self) -> str:
        return reverse_lazy('profile', kwargs={'username': self.request.user})

project_box/apps/mods/views.py
import os
from project_box.apps.mods.resize_mixin import ResizeImageMixin
from django.http.response import HttpResponseRedirect, JsonResponse
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from project_box.apps.mods.forms import ModCreateForm
from django.views.generic.base import TemplateView
from project_box.apps.mods.models import Mod, Screenshot, Type, SubType
import uuid
from django.contrib import messages
from project_box.storage_backends import MediaStorage


class ModDetailView(TemplateView):
    template_name = 'components/mods/singlemod.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mod_id = kwargs['pk']
        mod = Mod.objects.filter(id=mod_id).first()
        context['user'] = self.request.user
        context['mod'] = mod
        return context

    def get_client_ip(self):
        '''Get client IP address to allow for unique views on each mod.'''
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        return ip


class AddModView(LoginRequiredMixin, CreateView, ResizeImageMixin):
    template_name = 'components/mods/newmod.html'
    success_url = reverse_lazy('mods:mods-list')
    form_class = ModCreateForm
    success_message = "Mod created successfully"

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AddModView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.mod_file = self.request.FILES['mod_file']
        self.header_image = self.request.FILES['header_image']
        self.screenshots = self.request.FILES.getlist('screenshots')
        if len(self.screenshots) > 12:
            messages.error(
                self.request, 'A maximum of 12 screenshots is allowed.')
            return self.form_invalid(form)
        self.cover_image = self.request.FILES['cover_image']
        # Upload items to aws, store in well organized folders
        image_url = self.validate_and_upload_files(self.header_image, self.request.user, 'image')
        cover_image_url = self.validate_and_upload_files(self.cover_image, self.request.user, 'image')
        mod_file_url = self.validate_and_upload_files(self.mod_file, self.request.user)
        self.object = form.save(commit=False)
        self.object.image = image_url
        self.object.cover_image = cover_image_url
        self.object.mod_file = mod_file_url
        self.object.save()
        form.cleaned_data['simulator_'].mods.add(self.object)
        for f in self.screenshots:
            instance = Screenshot(image=f)
            instance.save()
            self.object.screenshots.add(instance)
        self.request.user.mods.add(self.object)
        return HttpResponseRedirect(self.get_success_url())

    def validate_and_upload_files(self, file_obj, user, image=None):
        # organize a path for the file in bucket
        if image:
            file_directory_within_bucket = 'user_mod_image_files/{username}'.format(username=user)
        else:
            file_directory_within_bucket = 'user_mod_files/{username}'.format(username=user)
        # synthesize a full file path; note that we included the filename
        file_path_within_bucket = os.path.join(
            file_directory_within_bucket,
            f'{uuid.uuid4()}.jpg'
        )
        media_storage = MediaStorage()
        # file_url = media_storage.url(file_path_within_bucket)
        return media_storage.save(file_path_within_bucket, file_obj)


class EditModView(LoginRequiredMixin, CreateView):
    template_name = 'components/mods/newmod.html'
    success_url = reverse_lazy('mods:mods-list')
    form_class = ModCreateForm
    success_message = "Mod created successfully"

    def get_initial(self, *args, **kwargs):
        initial = super(EditModView, self).get_initial(**kwargs)
        initial['title'] = 'My Title'
        return initial

    def form_valid(self, form):
        form.instance.created_by_user = self.request.user
        title = form.cleaned_data.get('title')
        description = form.cleaned_data.get('description')
        obj = Mod.objects.update(
            title=title,
            description=description,
        )
        obj.save()
        return super(EditModView, self).form_valid(form)


class ModsListView(TemplateView):
    template_name = 'components/mods/allmods.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mods = Type.objects.all().order_by('-name')
        context['user'] = self.request.user
        context['mods'] = mods
        return context


class CategoryView(TemplateView):
    template_name = 'components/mods/category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Type.objects.filter(id=self.kwargs['pk']).first()
        if category:
            category_mods = category.subtypes.all()
        else:
            category_mods = []
        context['user'] = self.request.user
        context['category'] = category
        context['category_mods'] = category_mods
        return context


class SubTypeView(TemplateView):
    template_name = 'components/mods/snippets/subtype.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mods = Mod.objects.filter(sub_type_mods=self.kwargs['type_']).filter(
            sub_type_mods__type_sub_types=self.kwargs['sim'])
        category = Type.objects.filter(id=self.kwargs['sim']).first()
        subtype = SubType.objects.filter(id=self.kwargs['type_']).first()
        context['user'] = self.request.user
        context['category'] = category
        context['subtype'] = subtype
        context['mods'] = mods
        return context

templates/components/mods/allmods.html
{% extends 'base.html' %} {% block maincontent %} {% load static %}
<div class="top-split" style="padding:150px 0">

  <section class="main-content container-fluid">
    <h4 class="main-title">All Simulators</h4>
    <br>
    <br>
    <br>
    <div class="upcoming-contens">
      <ul class="favorites-slider list-inline row p-0 mb-0">
        {% for mod in mods %}
        <li class="slide-item">
          <a href="{% url 'mods:category' mod.id %}">
            <div class="block-images position-relative">
              <div class="img-box">
                <img src="{% static 'images/favorite/04.png' %}" class="img-fluid" alt="" />
              </div>
              <div class="block-description">
                <h6 class="iq-title">
                  {{mod.name}}
                </h6>
              </div>
            </div>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </section>
  {% endblock %}

templates/components/mods/category.html
{% extends 'base.html' %} {% block maincontent %} {% load static %}
{% if category and category_mods %}
<div class="top-split" style="padding: 150px 0">
  <section id="iq-upcoming-movie mt-8">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12 overflow-hidden">
          <div class="iq-main-header d-flex align-items-center justify-content-between">
            <h4 class="main-title">{{category.name}} Sub Categories</h4>
          </div>
          <br>
          <br>
          <br>
          <div class="upcoming-contens">
            <ul class="favorites-slider list-inline row p-0 mb-0">
              {% for mod in category_mods %}
              <li class="slide-item">
                <a href="{% url 'mods:subtype' sim=category.id type_=mod.id %}">
                  <div class="block-images position-relative">
                    <div class="img-box">
                      <img src="{% static 'images/favorite/04.png' %}" class="img-fluid" alt="" />
                    </div>
                    <div class="block-description">
                      <h6 class="iq-title">
                        {{mod.name}}
                      </h6>
                    </div>
                  </div>
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% else %}
<div class="main-content container-fluid" style="padding-top: 250px">
  <h3>Simulator sub categories not found!</h3>
  <br /><br />
  <p>The simulator you tried viewing does not exist in our system or does not have any sub categories.</p>
  <br />

  <div class="sign-info">
    <a href="{% url 'authentication:index' %}" class="btn btn-hover">Take me back home</a>
  </div>
</div>
{% endif %} {% endblock %}

templates/components/mods/featured.html
{%load static%}

<section id="parallex" class="parallax-window">
  <div class="container-fluid h-100">
    <div
      class="row align-items-center justify-content-center h-100 parallaxt-details"
    >
      <div class="col-lg-4 r-mb-23">
        <div class="text-left">
<br>
          <a href="{% url 'mods:mod-detail' featured.id %}">
            <img
              src="{{featured.header_image.url}}"
              class="img-fluid"
              alt="{{featured.title}}"
            />
          </a>
          <br><br>

                  <h3 class="iq-title">
                    <a href="{% url 'mods:mod-detail' featured.id %}">{{featured.title}}</a>
                  </h3>
                  <br><br>
          <div class="movie-time d-flex align-items-center mb-3">
            <div class="badge badge-secondary mr-3">{{featured.downloads.count}} Downloads</div>
            <h6 class="text-white">{% for typ in featured.type_mods.all %} | {{typ.name}}{% endfor %}</h6>
          </div>

                <div class="text-primary title genres">
                  File Size: <span class="text-body">{{featured.mod_file.size | filesizeformat}}</span>
                </div>
          <p class="text-sm-left">
            {{featured.description|safe}}
          </p>
          <div class="parallax-buttons">
            <a href="{% url 'mods:mod-detail' featured.id %}" class="btn btn-hover">Download</a>
            <a href="{% url 'mods:mod-detail' featured.id %}" class="btn btn-link">More details</a>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="parallax-img">
          <a href="{% url 'mods:mod-detail' featured.id %}">
            <img
              src="{{featured.cover_image.url}}"
              class="img-fluid w-100"
              alt="{{featured.title}}"
            />
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

templates/components/mods/newmod.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{%block maincontent %}
<section class="sign-in-page">
  <div class="top-split" style="padding:150px 0;">
    {% comment %}
    <video autoplay muted loop id="myVideo">
      <source src="{%static 'images/bg-video.mp4' %}" type="video/mp4" />
    </video>
    {% endcomment %}
    <div class="container">
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-8 col-md-12 align-self-center mt-8 p-5">
          <div class="sign-user_card">
            <div class="sign-in-page-data">
              <div class="sign-in-from w-100 m-auto">
                <h3 class="text-center">Create an Add-On</h3>
                {{ form.media }}
                <form class="mt-12" method="post" enctype="multipart/form-data">
                  <br />
                  {% if messages %}
                  {% for message in messages %}
                  {% if message.tags == "success" %}
                  <p class="successField">
                    {{message}}
                  </p>
                  {%else%}
                  <p class="errorField">
                    {{message}}
                  </p>
                  {% endif %}
                  {% endfor %}
                  {%endif%}
                  {% csrf_token %} {{ form|crispy }}
                  <br>
                  <button type="submit" class="btn btn-hover my-2">
                    Save
                  </button>
                </form>
              </div>
            </div>
            <div class="mt-3">
              <div class="d-flex justify-content-start links">
                Or?
                <a href="{%url 'mods:mods-list' %}" class="text-primary ml-2">View All Mods</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/components/mods/singlemod.html
{% extends 'base.html' %} {% block maincontent %} {% load static %}
{% if mod %}
<section class="banner-wrapper overlay-wrapper iq-main-slider" style="background-image: url({{mod.cover_image.url}});">
  <div class="banner-caption">
    <div class="position-relative mb-4">
      <a href="#" class="d-flex align-items-center">
        <div class="play-button">
          <i class="fa fa-download"></i>
        </div>
        <h4 class="w-name text-white font-weight-700">Download</h4>
      </a>
    </div>
    <br /><br />
    {% comment %}
    <ul class="list-inline p-0 m-0 share-icons music-play-lists">
      <li>
        <span><i class="ri-heart-fill"></i></span>
      </li>
      <li class="share">
        <span><i class="ri-share-fill"></i></span>
        <div class="share-box">
          <div class="d-flex align-items-center">
            <a href="#" class="share-ico"><i class="ri-facebook-fill"></i></a>
            <a href="#" class="share-ico"><i class="ri-twitter-fill"></i></a>
            <a href="#" class="share-ico"><i class="ri-links-fill"></i></a>
          </div>
        </div>
      </li>
    </ul>
    {% endcomment %}
  </div>
</section>
<!-- Banner End -->
<!-- MainContent -->
<div class="main-content">
  <section class="movie-detail container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="trending-info g-border">
          <h1 class="trending-text big-title text-uppercase mt-0">
            {{mod.title}}
          </h1>
          <ul class="p-0 list-inline d-flex align-items-center movie-content">
            {% for typ in mod.type_mods.all %}
            <li class="text-white">| {{typ}}</li>
            {% endfor %}
          </ul>
          <div class="d-flex align-items-center text-white text-detail">
            <span class="badge badge-secondary p-3"
              >{{mod.downloads.count}}</span
            >
            <span class="ml-3">Downloads</span>
          </div>
          {% comment %}
          <div class="d-flex align-items-center series mb-4">
            <a href="javascript:void();"
              ><img
                src="{% static 'images/trending/trending-label.png' %}"
                class="img-fluid"
                alt=""
            /></a>
            <span class="text-gold ml-3">#2 in Most Downloaded Today</span>
          </div>
          {% endcomment %}
          <p class="trending-dec w-100 mb-0">{{mod.description|safe}}</p>
        </div>
      </div>
    </div>
  </section>
  <section class="container-fluid seasons">
    <ul
      class="trending-pills d-flex nav nav-pills align-items-center text-center s-margin"
      role="tablist"
    >
      <li class="nav-item">
        <a
          class="nav-link active show"
          data-toggle="pill"
          href="#episodes"
          role="tab"
          aria-selected="true"
          >Images</a
        >
      </li>
    </ul>
    <div class="tab-content">
      <div id="episodes" class="tab-pane fade active show" role="tabpanel">
        <div class="block-space">
          <div class="row">
            <div class="col-1-5 col-md-6 iq-mb-30">
              <div class="epi-box">
                <div class="epi-img position-relative">
                  <img
                    src="{{mod.header_image.url}}"
                    class="img-fluid img-zoom"
                    alt=""
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% else %}
<div class="main-content container-fluid"  style="padding-top:250px">
  <h3>Add-on not found!</h3>
  <br><br>
  <p>The mod you tried viewing does not exist in our system. 
  </p><br>
  <div class="sign-info">
    <a href="{% url 'authentication:index' %}" class="btn btn-hover">Take me back home</a>
  </div>
</div>
{% endif %}
{%endblock%}

templates/components/mods/slider.html
{% load static%}
<!-- Slider Start -->
<section id="home" class="iq-main-slider p-0">
  <div id="home-slider" class="slider m-0 p-0">
    <div class="slide slick-bg s-bg-1" style="background-image: url({{featured.cover_image.url}})">
      <div class="container-fluid position-relative h-100">
        <div class="slider-inner h-100">
          <div class="row align-items-center h-100">
            <div class="col-xl-6 col-lg-12 col-md-12">
              <a href="javascript:void(0);">
                <div class="channel-logo" data-animation-in="fadeInLeft" data-delay-in="0.5">
                  Featured
                </div>
              </a>
              <br>
              <h2 class="slider-text big-title title text-uppercase" data-animation-in="fadeInLeft" data-delay-in="0.6">
                {{featured.title}}
              </h2>


              <!-- <div class="d-flex align-items-center" data-animation-in="fadeInUp" data-delay-in="1">
                               
                              <span class="badge badge-secondary p-2">18+</span>
                              <span class="ml-3">2 Seasons</span>
                           </div> -->
              <p data-animation-in="fadeInUp" data-delay-in="1.2">
                {{featured.description|safe}}
              </p>
              <div class="trending-list" data-wp_object-in="fadeInUp" data-delay-in="1.2">

                <div class="text-primary title genres">
                  File Size: <span class="text-body">{{featured.mod_file.size | filesizeformat}}</span>
                </div>
              </div>
              <div class="d-flex align-items-center r-mb-23" data-animation-in="fadeInUp" data-delay-in="1.2">
                <a href="{% url 'mods:mod-detail' featured.id %}" class="btn btn-hover iq-button"><i
                    class="fa fa-play mr-2" aria-hidden="true"></i>Download
                  Now</a>
                <a href="{% url 'mods:mod-detail' featured.id %}" class="btn btn-link">More details</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none">
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44" width="44px" height="44px" id="circle" fill="none"
      stroke="currentColor">
      <circle r="20" cy="22" cx="22" id="test"></circle>
    </symbol>
  </svg>
</section>
<!-- Slider End -->